name: fr_florent59_plugin
main: fr.florent59.plugin.Plugin
version: 1.0.0
description: Pour rejoindre une team
author: Florent59
commands:
 jointeam:
  description: Pour rejoindre une team
 houe:
  description: Pour ajouter une houe